# Generated by Django 2.1.7 on 2020-02-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
